// Seed du catalogue produits GAME SHOP 221
// Exécuter : bun run /home/z/my-project/scripts/seed.ts

import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

const products = [
  // ========== COMPTES GAMING ==========
  {
    name: "Compte Fortnite OG",
    description: "Compte Fortnite avec skins rares (Renégat, Skull Trooper), 30+ skins, 1500 V-Bucks.",
    price: 25000,
    oldPrice: 32000,
    category: "comptes",
    game: "Fortnite",
    badge: "POPULAIRE",
    emoji: "🎯",
    popular: true,
    instantDelivery: true,
    deliveryContent: "Email: game_shop_221@gmail.com\nMot de passe: GameShop@221\nCode 2FA: 482 915\n\nLes skins sont déjà équipés. Changez le mot de passe après connexion.",
    deliveryTime: null,
  },
  {
    name: "Compte Valorant",
    description: "Compte Valorant avec 5 skins armes premium (Reaver, Prime), tous agents débloqués, rank Or.",
    price: 30000,
    category: "comptes",
    game: "Valorant",
    emoji: "🔫",
    popular: false,
    instantDelivery: false,
    deliveryContent: null,
    deliveryTime: "10-30 min",
  },
  {
    name: "Compte GTA V Online",
    description: "Compte GTA Online moddé : 500M$, rank 200, toutes les voitures, armes débloquées.",
    price: 15000,
    oldPrice: 20000,
    category: "comptes",
    game: "GTA V",
    badge: "PROMO",
    emoji: "🚗",
    popular: true,
    instantDelivery: true,
    deliveryContent: "Plateforme: PC (Steam/Epic)\nEmail: gtashop221@gmail.com\nMot de passe: GTA@Shop221\n\nLe compte est moddé. Connectez-vous en mode story d'abord puis online.",
    deliveryTime: null,
  },
  {
    name: "Compte PUBG Mobile",
    description: "Compte PUBG Mobile : 10 000 UC, skins M416 Mythique, Conqueror S25, 80+ skins.",
    price: 22000,
    category: "comptes",
    game: "PUBG Mobile",
    emoji: "🎯",
    popular: false,
    instantDelivery: false,
    deliveryContent: null,
    deliveryTime: "15-45 min",
  },
  {
    name: "Compte Free Fire",
    description: "Compte Free Fire : 5000 diamants, 15 personnages, AWM Élite, passe de saison max.",
    price: 12000,
    category: "comptes",
    game: "Free Fire",
    emoji: "🔥",
    popular: false,
    instantDelivery: false,
    deliveryContent: null,
    deliveryTime: "10-30 min",
  },
  {
    name: "Compte Call of Duty Mobile",
    description: "Compte CODM : 2000 CP, 30 skins épiques, BP Mythique, rank Légendaire.",
    price: 18000,
    category: "comptes",
    game: "COD Mobile",
    emoji: "🎖️",
    popular: false,
    instantDelivery: false,
    deliveryContent: null,
    deliveryTime: "15-30 min",
  },

  // ========== RECHARGES ==========
  {
    name: "325 UC PUBG Mobile",
    description: "Recharge instantanée 325 UC PUBG Mobile. Livraison automatique après paiement.",
    price: 5000,
    category: "recharges",
    game: "PUBG Mobile",
    badge: "TOP VENTE",
    emoji: "💎",
    popular: true,
    instantDelivery: true,
    deliveryContent: "Votre recharge de 325 UC est en cours de traitement automatique.\n\nConnectez-vous à PUBG Mobile avec votre ID joueur, les UC seront créditées sous 2-5 minutes.\n\nSi rien n'apparaît après 10 min, contactez-nous sur WhatsApp avec votre référence de commande.",
    deliveryTime: null,
  },
  {
    name: "660 UC PUBG Mobile",
    description: "Recharge 660 UC PUBG Mobile. Bonus 60 UC inclus. Livraison automatique.",
    price: 9500,
    category: "recharges",
    game: "PUBG Mobile",
    emoji: "💎",
    popular: false,
    instantDelivery: true,
    deliveryContent: "Votre recharge de 660 UC (+60 bonus) est en cours de traitement automatique.\n\nLes UC seront créditées sur votre compte PUBG sous 2-5 minutes.",
    deliveryTime: null,
  },
  {
    name: "1800 UC PUBG Mobile",
    description: "Recharge 1800 UC PUBG Mobile + bonus. Idéal pour Royale Pass et chests.",
    price: 23000,
    oldPrice: 25000,
    category: "recharges",
    game: "PUBG Mobile",
    badge: "ÉCONOMIE",
    emoji: "💎",
    popular: false,
    instantDelivery: true,
    deliveryContent: "Votre recharge de 1800 UC (+bonus) est en cours de traitement automatique.\n\nLes UC seront créditées sous 2-5 minutes.",
    deliveryTime: null,
  },
  {
    name: "310 Diamants Free Fire",
    description: "Recharge 310 diamants Free Fire. Livraison automatique après paiement.",
    price: 4000,
    category: "recharges",
    game: "Free Fire",
    emoji: "🔥",
    popular: true,
    instantDelivery: true,
    deliveryContent: "Votre recharge de 310 diamants Free Fire est en cours de traitement automatique.\n\nLes diamants seront crédités sous 2-5 minutes.",
    deliveryTime: null,
  },
  {
    name: "520 Diamants Free Fire",
    description: "Recharge 520 diamants Free Fire. Bonus inclus, livraison automatique.",
    price: 6500,
    category: "recharges",
    game: "Free Fire",
    emoji: "🔥",
    popular: false,
    instantDelivery: true,
    deliveryContent: "Votre recharge de 520 diamants Free Fire est en cours de traitement automatique.\n\nLes diamants seront crédités sous 2-5 minutes.",
    deliveryTime: null,
  },
  {
    name: "1060 Diamants Free Fire",
    description: "Recharge 1060 diamants Free Fire + bonus. Pour passe Elite et boîtes premium.",
    price: 12000,
    category: "recharges",
    game: "Free Fire",
    emoji: "🔥",
    popular: false,
    instantDelivery: true,
    deliveryContent: "Votre recharge de 1060 diamants Free Fire est en cours de traitement automatique.\n\nLes diamants seront crédités sous 2-5 minutes.",
    deliveryTime: null,
  },
  {
    name: "1000 VP Valorant",
    description: "Recharge 1000 Points Vanguard Valorant. Achetez skins dans la boutique.",
    price: 8000,
    category: "recharges",
    game: "Valorant",
    emoji: "🔫",
    popular: false,
    instantDelivery: true,
    deliveryContent: "Votre recharge de 1000 VP Valorant est en cours de traitement automatique.\n\nLes VP seront crédités sur votre compte sous 5-10 minutes.",
    deliveryTime: null,
  },
  {
    name: "400 CP Call of Duty Mobile",
    description: "Recharge 400 CP COD Mobile. Pour tirages et Battle Pass.",
    price: 5500,
    category: "recharges",
    game: "COD Mobile",
    emoji: "🎖️",
    popular: false,
    instantDelivery: true,
    deliveryContent: "Votre recharge de 400 CP COD Mobile est en cours de traitement automatique.\n\nLes CP seront crédités sous 5-10 minutes.",
    deliveryTime: null,
  },
  {
    name: "1000 V-Bucks Fortnite",
    description: "Recharge 1000 V-Bucks Fortnite. Achetez skins, danses et Battle Pass.",
    price: 9000,
    category: "recharges",
    game: "Fortnite",
    emoji: "🎯",
    popular: false,
    instantDelivery: true,
    deliveryContent: "Votre recharge de 1000 V-Bucks Fortnite est en cours de traitement automatique.\n\nLes V-Bucks seront crédités sous 5-10 minutes.",
    deliveryTime: null,
  },

  // ========== CARTES CADEAUX ==========
  {
    name: "Carte Steam 10€",
    description: "Carte cadeau Steam 10€. Code envoyé automatiquement après paiement.",
    price: 7500,
    category: "cartes",
    game: "Steam",
    emoji: "🎮",
    popular: true,
    instantDelivery: true,
    deliveryContent: "🎮 CODE CARTE STEAM 10€\n\nCode: 5X7Y-9PZK-3M2N\n\nComment l'utiliser:\n1. Ouvrez Steam\n2. Cliquez sur 'Jeux' → 'Activer un produit sur Steam'\n3. Suivez les instructions et entrez le code\n4. Le montant sera crédité sur votre compte Steam",
    deliveryTime: null,
  },
  {
    name: "Carte Steam 25€",
    description: "Carte cadeau Steam 25€. Code digital livré automatiquement.",
    price: 17000,
    oldPrice: 18500,
    category: "cartes",
    game: "Steam",
    badge: "PROMO",
    emoji: "🎮",
    popular: false,
    instantDelivery: true,
    deliveryContent: "🎮 CODE CARTE STEAM 25€\n\nCode: 8KQF-4RTY-6WZP\n\nComment l'utiliser:\n1. Ouvrez Steam\n2. Cliquez sur 'Jeux' → 'Activer un produit sur Steam'\n3. Suivez les instructions et entrez le code",
    deliveryTime: null,
  },
  {
    name: "Carte Google Play 15€",
    description: "Carte Google Play 15€. Pour apps, jeux, abonnements Android. Code digital immédiat.",
    price: 10000,
    category: "cartes",
    game: "Google Play",
    emoji: "📱",
    popular: false,
    instantDelivery: true,
    deliveryContent: "📱 CODE GOOGLE PLAY 15€\n\nCode: 4G7H-2J3K-8M9N-1PQR\n\nComment l'utiliser:\n1. Ouvrez Play Store\n2. Menu → 'Utiliser un code'\n3. Saisissez le code ci-dessus",
    deliveryTime: null,
  },
  {
    name: "Carte Google Play 25€",
    description: "Carte Google Play 25€. Idéale pour achats in-app et abonnements premium.",
    price: 17500,
    category: "cartes",
    game: "Google Play",
    emoji: "📱",
    popular: false,
    instantDelivery: true,
    deliveryContent: "📱 CODE GOOGLE PLAY 25€\n\nCode: 7K2M-9P4Q-R6T8-V3WX\n\nComment l'utiliser:\n1. Ouvrez Play Store\n2. Menu → 'Utiliser un code'\n3. Saisissez le code ci-dessus",
    deliveryTime: null,
  },
  {
    name: "Carte PSN 10€",
    description: "Carte PlayStation Network 10€. Pour achats jeux PS4/PS5, abonnement PS Plus.",
    price: 8000,
    category: "cartes",
    game: "PlayStation",
    emoji: "🎮",
    popular: false,
    instantDelivery: true,
    deliveryContent: "🎮 CODE PSN 10€\n\nCode: 9F2K-4P7M-Q3R8\n\nComment l'utiliser:\n1. Sur votre PS4/PS5, allez dans PlayStation Store\n2. En bas : 'Utiliser un code'\n3. Saisissez le code ci-dessus",
    deliveryTime: null,
  },
  {
    name: "Carte iTunes 25$",
    description: "Carte iTunes/App Store 25$. Pour apps iOS, musique, abonnements iCloud.",
    price: 17000,
    category: "cartes",
    game: "Apple",
    emoji: "🍎",
    popular: false,
    instantDelivery: true,
    deliveryContent: "🍎 CODE ITUNES 25$\n\nCode: X9K7M2P4Q8RTVW\n\nComment l'utiliser:\n1. Ouvrez l'App Store ou iTunes\n2. Cliquez sur 'Utiliser un code cadeau'\n3. Saisissez le code ci-dessus",
    deliveryTime: null,
  },
  {
    name: "Netflix 1 Mois Premium",
    description: "Compte Netflix 4K Ultra HD 1 mois. Profil personnel, accès partagé garanti.",
    price: 9000,
    category: "cartes",
    game: "Netflix",
    badge: "TOP VENTE",
    emoji: "🎬",
    popular: true,
    instantDelivery: true,
    deliveryContent: "🎬 COMPTE NETFLIX PREMIUM 4K - 1 MOIS\n\nEmail: netflixgs221@gmail.com\nMot de passe: Netflix@221\n\nVotre profil dédié: 'GS221-User'\n\nQualité: 4K Ultra HD + HDR\nÉcrans simultanés: 4\nNe modifiez PAS le mot de passe.",
    deliveryTime: null,
  },
  {
    name: "Spotify Premium 3 Mois",
    description: "Abonnement Spotify Premium 3 mois. Musique sans pub, téléchargement offline.",
    price: 9500,
    category: "cartes",
    game: "Spotify",
    emoji: "🎵",
    popular: false,
    instantDelivery: true,
    deliveryContent: "🎵 COMPTE SPOTIFY PREMIUM - 3 MOIS\n\nEmail: spotifygs221@gmail.com\nMot de passe: Spotify@221\n\nPremium actif pour 90 jours.\nNe modifiez PAS le mot de passe.",
    deliveryTime: null,
  },
];

async function main() {
  console.log(`Seed: ${products.length} produits a inserer...`);

  await db.product.deleteMany({});
  console.log("Anciens produits supprimes");

  for (const p of products) {
    await db.product.create({
      data: {
        name: p.name,
        description: p.description,
        price: p.price,
        oldPrice: p.oldPrice ?? null,
        category: p.category,
        game: p.game ?? null,
        emoji: p.emoji,
        badge: p.badge ?? null,
        popular: p.popular,
        instantDelivery: p.instantDelivery,
        deliveryContent: p.deliveryContent ?? null,
        deliveryTime: p.deliveryTime ?? null,
        stock: 99,
        active: true,
      },
    });
  }

  const count = await db.product.count();
  console.log(`${count} produits inseres`);

  const instant = await db.product.count({ where: { instantDelivery: true } });
  console.log(`${instant} produits en livraison instantanee`);
}

main()
  .catch((e) => {
    console.error("Erreur lors du seed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
